package com.example.silviu086.licenta;

import java.util.ArrayList;

/**
 * Created by Silviu086 on 10.05.2016.
 */
public class OraseRomania {
        private static OraseRomania instance = null;
        private ArrayList<String> listaOrase;

        public static OraseRomania getInstance() {
        if (instance == null) {
            instance = new OraseRomania();
        }
        return instance;
        }

        private OraseRomania() {
                listaOrase = new ArrayList<>();
                String[] array = new String[]{
                "Bucuresti",
                "Cluj-Napoca,Cluj",
                "Timisoara,Timis",
                "Iasi,Iasi",
                "Constanta,Constanta",
                "Craiova,Dolj",
                "Brasov,Brasov",
                "Galati,Galati",
                "Ploiesti,Prahova",
                "Oradea,Bihor",
                "Braila,Braila",
                "Arad,Arad",
                "Pitesti,Arges",
                "Sibiu,Sibiu",
                "Bacau,Bacau",
                "Targu Mures,Mures",
                "Baia Mare,Maramures",
                "Buzau,Buzau",
                "Botosani,Botosani",
                "Satu Mare,Satu Mare",
                "Ramnicu Valcea,Valcea",
                "Drobeta-Turnu Severin,Mehedinti",
                "Suceava,Suceava",
                "Piatra Neamt,Neamt",
                "Targu Jiu,Gorj",
                "Targoviste,Dambovita",
                "Focsani,Vrancea",
                "Bistrita,Bistrita-Nasaud",
                "Resita,Caras-Severin",
                "Tulcea,Tulcea",
                "Slatina,Olt",
                "Calarasi,Calarasi",
                "Alba Iulia,Alba",
                "Giurgiu,Giurgiu",
                "Deva,Hunedoara",
                "Hunedoara,Hunedoara",
                "Zalau,Salaj",
                "Sfantu Gheorghe,Covasna",
                "Barlad,Vaslui",
                "Vaslui,Vaslui	",
                "Roman,Neamt",
                "Slobozia,Ialomita",
                "Turda,Cluj",
                "Medias,Sibiu",
                "Alexandria,Teleorman",
                "Voluntari,Ilfov",
                "Lugoj,Timis",
                "Medgidia,Constanta",
                "Onesti,Bacau",
                "Miercurea Ciuc,Harghita",
                "Sighetu Marmatiei,Maramures",
                "Petrosani,Hunedoara",
                "Mangalia,Constanta",
                "Tecuci,Galati",
                "Ramnicu Sarat,Buzau",
                "Pascani,Iasi",
                "Dej,Cluj",
                "Reghin,Mures",
                "Navodari,Constanta",
                "Odorheiu Secuiesc,Harghita",
                "Campina,Prahova	",
                "Mioveni,Arges",
                "Campulung,Arges",
                "Caracal,Olt",
                "Sacele,Brasov",
                "Fagaras,Brasov",
                "Fetesti,Ialomita	",
                "Sighisoara,Mures",
                "Borsa,Maramures",
                "Rosiorii de Vede,Teleorman",
                "Curtea de Arges,Arges",
                "Sebes,Alba",
                "Husi,Vaslui",
                "Falticeni,Suceava",
                "Pantelimon,Ilfov",
                "Oltenita,Calarasi",
                "Turnu Magurele,Teleorman",
                "Caransebes,Caras-Severin",
                "Dorohoi,Botosani",
                "Vulcan,Hunedoara",
                "Radauti,Suceava",
                "Zarnesti,Brasov",
                "Lupeni,Hunedoara",
                "Aiud,Alba",
                "Petrila,Hunedoara",
                "Buftea,Ilfov",
                "Moinesti,Bacau",
                "Tarnaveni,Mures",
                "Campia Turzii,Cluj",
                "Popesti-Leordeni,Ilfov",
                "Gherla,Cluj",
                "Carei,Satu Mare",
                "Cugir,Alba",
                "Blaj,Alba",
                "Codlea,Brasov",
                "Comanesti,Bacau",
                "Targu Neamt,Neamt",
                "Motru,Gorj",
                "Targu Secuiesc,Covasna",
                "Moreni,Dambovita",
                "Gheorgheni,Harghita",
                "Baicoi,Prahova",
                "Orastie,Hunedoara",
                "Salonta,Bihor",
                "Bals,Olt",
                "Dragasani,Valcea",
                "Bailesti,Dolj",
                "Calafat,Dolj",
                "Filiasi,Dolj",
                "Cernavoda,Constanta",
                "Campulung Moldovenesc,Suceava",
                "Breaza,Prahova",
                "Marghita,Bihor",
                "Baia Sprie,Maramures",
                "Ludus,Mures",
                "Corabia,Olt",
                "Adjud,Vrancea",
                "Viseu de Sus,Maramures",
                "Bragadiru,Ilfov",
                "Bocsa,Caras-Severin",
                "Rasnov,Brasov",
                "Urziceni,Ialomita",
                "Brad,Hunedoara",
                "Stefanesti,Arges",
                "Pucioasa,Dambovita",
                "Vatra Dornei,Suceava",
                "Cisnadie,Sibiu",
                "Mizil,Prahova",
                "Toplita,Harghita",
                "Chitila,Ilfov",
                "Simleu Silvaniei,Salaj",
                "Buhusi,Bacau",
                "Vicovu de Sus,Suceava",
                "Zimnicea,Teleorman",
                "Gaesti,Dambovita",
                "Gura Humorului,Suceava",
                "Otopeni,Ilfov",
                "Ocna Mures,Alba",
                "Ovidiu,Constanta",
                "Avrig,Sibiu",
                "Simeria,Hunedoara",
                "Pecica,Arad",
                "Dabuleni,Dolj",
                "Bolintin-Vale,Giurgiu",
                "Rovinari,Gorj",
                "Comarnic,Prahova",
                "Valenii de Munte,Prahova",
                "Sannicolau Mare,Timis",
                "Darmanesti,Bacau",
                "Moldova Noua,Caras-Severin",
                "Targu Lapus,Maramures",
                "Sacueni,Bihor",
                "Videle,Teleorman",
                "Scornicesti,Olt",
                "Boldesti-Scaeni,Prahova",
                "Santana,Arad",
                "Targu Ocna,Bacau",
                "Magurele,Ilfov",
                "Calan,Hunedoara",
                "Beclean,Bistrita-Nasaud",
                "tandarei,Ialomita",
                "Sovata,Mures",
                "Oravita,Caras-Severin",
                "Jibou,Salaj",
                "Urlati,Prahova",
                "Costesti,Arges",
                "Harlau,Iasi",
                "Beius,Bihor",
                "Ianca,Braila",
                "Jimbolia,Timis",
                "Topoloveni,Arges",
                "Draganesti-Olt,Olt",
                "Sinaia,Prahova",
                "Nehoiu,Buzau",
                "Covasna,Covasna",
                "Negresti-Oas,Satu Mare",
                "Strehaia,Mehedinti",
                "Dolhasca,Suceava",
                "Orsova,Mehedinti",
                "Valea lui Mihai,Bihor",
                "Lipova,Arad",
                "Murfatlar,Constanta",
                "Alesd,Bihor",
                "Darabani,Botosani",
                "Cristuru Secuiesc,Harghita",
                "Flamanzi,Botosani",
                "Marasesti,Vrancea",
                "Sangeorz-Bai,Bistrita-Nasaud",
                "Liteni,Suceava",
                "Targu Frumos,Iasi",
                "Titu,Dambovita",
                "Hateg,Hunedoara",
                "Otelu Rosu,Caras-Severin",
                "Ineu,Arad",
                "Nasaud,Bistrita-Nasaud",
                "Huedin,Cluj",
                "Odobesti,Vrancea",
                "Harsova,Constanta",
                "Bumbesti-Jiu,Gorj",
                "Seini,Maramures",
                "Salcea,Suceava",
                "Podu Iloaiei,Iasi",
                "Eforie,Constanta",
                "Uricani,Hunedoara",
                "Baraolt,Covasna",
                "Busteni,Prahova",
                "Tasnad,Satu Mare",
                "Iernut,Mures",
                "Agnita,Sibiu",
                "Roznov,Neamt",
                "Babadag,Tulcea",
                "Babeni,Valcea",
                "Targu Carbunesti,Gorj",
                "Negresti,Vaslui",
                "Recas,Timis",
                "Siret,Suceava",
                "Macin,Tulcea",
                "Chisineu-Cris,Arad",
                "Plopeni,Prahova",
                "Mihailesti,Giurgiu",
                "somcuta Mare,Maramures",
                "Fieni,Dambovita",
                "Intorsura Buzaului,Covasna",
                "Calimanesti,Valcea",
                "Panciu,Vrancea",
                "Nadlac,Arad",
                "Zlatna,Alba",
                "Patarlagele,Buzau",
                "Cehu Silvaniei,Salaj",
                "Amara,Ialomita",
                "Ulmeni,Maramures",
                "Victoria,Brasov",
                "Budesti,Calarasi",
                "Anina,Caras-Severin",
                "Dumbraveni,Sibiu",
                "Campeni,Alba",
                "Pogoanele,Buzau",
                "Tautii-Magheraus,Maramures",
                "Tismana,Gorj",
                "Curtici,Arad",
                "Techirghiol,Constanta",
                "Sarmasu,Mures",
                "Vlahita,Harghita",
                "Cajvana,Suceava",
                "Saveni,Botosani",
                "Segarcea,Dolj",
                "Pancota,Arad",
                "Livada,Satu Mare",
                "Racari,Dambovita",
                "Ungheni,Mures",
                "Faget,Timis",
                "Talmaciu,Sibiu",
                "Buzias,Timis",
                "Fundulea,Calarasi",
                "Murgeni,Vaslui",
                "Teius,Alba",
                "Insuratei,Braila",
                "Bicaz,Neamt",
                "Targu Bujor,Galati",
                "Stei,Bihor",
                "Lehliu Gara,Calarasi",
                "Horezu,Valcea",
                "Deta,Timis",
                "Slanic,Prahova",
                "Piatra-Olt,Olt",
                "Ardud,Satu Mare",
                "Balan,Harghita",
                "Sebis,Arad",
                "Frasin,Suceava",
                "Brezoi,Valcea",
                "Potcoava,Olt",
                "Gataia,Timis",
                "Brosteni,Suceava",
                "Novaci,Gorj",
                "Miercurea Nirajului,Mures",
                "Baia de Arama,Mehedinti",
                "Copsa Mica,Sibiu",
                "Vanju Mare,Mehedinti",
                "Stefanesti,Botosani",
                "Sangeorgiu de Padure,Mures",
                "Geoagiu,Hunedoara",
                "Saliste,Sibiu",
                "Ciacova,Timis",
                "Baneasa,Constanta",
                "Rupea,Brasov",
                "Milisauti,Suceava",
                "Isaccea,Tulcea",
                "Abrud,Alba",
                "Negru Voda,Constanta",
                "Fierbinti-Targ,Ialomita",
                "Cavnic,Maramures",
                "Salistea de Sus,Maramures",
                "Baile Herculane,Caras-Severin",
                "Balcesti,Valcea",
                "Berbesti,Valcea",
                "Ghimbav,Brasov",
                "Predeal,Brasov",
                "Ticleni,Gorj",
                "Azuga,Prahova",
                "Aninoasa,Hunedoara",
                "Bucecea,Botosani",
                "Baile Olanesti,Valcea",
                "Slanic Moldova,Bacau",
                "Miercurea Sibiului,Sibiu",
                "Sulina,Tulcea",
                "Baia de Aries,Alba",
                "Faurei,Braila",
                "Ocna Sibiului,Sibiu",
                "Bechet,Dolj",
                "Cazanesti,Ialomita",
                "Dragomiresti,Maramures",
                "Ocnele Mari,Valcea",
                "Beresti,Galati",
                "Borsec,Harghita",
                "Baile Govora,Valcea",
                "Vascau,Bihor",
                "Nucet,Bihor",
                "Solca,Suceava",
                "Baile Tusnad,Harghita"
                };
                for(int i=0;i<array.length;i++){
                        listaOrase.add(array[i]);
                }
        }

        public ArrayList<String> getListaOrase(){
                return this.listaOrase;
        }

        public boolean find(String oras){
                for(int i=0;i<listaOrase.size();i++){
                        if(listaOrase.get(i).equalsIgnoreCase(oras)){
                                return true;
                        }
                }
                return false;
        }
}
